# Generated by Django 5.0 on 2024-01-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings', verbose_name='Логотип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('context', models.TextField(verbose_name='Описание Заголовки')),
                ('image_about', models.ImageField(upload_to='about', verbose_name='Фото')),
                ('description_about', models.TextField(verbose_name='Описание О нас')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовка-2')),
                ('title3', models.CharField(max_length=155, verbose_name='Заголовка-3')),
                ('title4', models.CharField(max_length=155, verbose_name='Заголовка-4')),
                ('title5', models.CharField(max_length=155, verbose_name='Заголовка-5')),
                ('title6', models.CharField(max_length=155, verbose_name='Заголовка-6')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка Главного Строницы',
            },
        ),
    ]
