# Generated by Django 5.0 on 2024-01-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_aboutstatic_remove_settings_logo_settings_logo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo1',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo2',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Логотип-2'),
            preserve_default=False,
        ),
    ]
