# Generated by Django 5.0 on 2024-01-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_settings_logo1_alter_settings_logo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image',
            field=models.ImageField(default=1, upload_to='settings', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
