# Generated by Django 5.0 on 2024-01-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_settings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstatic',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Статистика'),
        ),
    ]
