# Generated by Django 5.0 on 2024-01-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_aboutstatic_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstatic',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='settings.settings'),
            preserve_default=False,
        ),
    ]
