# Generated by Django 5.0 on 2024-01-07 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_aboutstatic_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='settings.settings')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.DeleteModel(
            name='AboutStatic',
        ),
    ]
