# Generated by Django 5.0 on 2024-01-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_about_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статистика'),
        ),
    ]
