# Generated by Django 5.0 on 2024-01-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_stati_remove_about_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interesting', verbose_name='Фото')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('context', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Интересные факты',
            },
        ),
        migrations.AlterModelOptions(
            name='stati',
            options={'verbose_name': '', 'verbose_name_plural': 'Статистика'},
        ),
    ]
