# Generated by Django 5.0 on 2024-01-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_interesting_alter_stati_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesting',
            name='cart',
            field=models.CharField(default=1, max_length=20, verbose_name='Корзина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interesting',
            name='price',
            field=models.CharField(default=1, max_length=20, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
