# Generated by Django 5.0 on 2024-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_product_delete_interesting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interesting', verbose_name='Фото')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Интересные факторы',
            },
        ),
    ]
