# Generated by Django 5.0 on 2024-01-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_interesting_settings_product_settings_stati_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='settings',
        ),
        migrations.AlterField(
            model_name='interesting',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesting', to='settings.product'),
        ),
    ]
