# Generated by Django 5.0 on 2024-01-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_remove_product_settings_alter_interesting_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='settings.settings'),
            preserve_default=False,
        ),
    ]
