# Generated by Django 5.0 on 2024-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_product_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=155, verbose_name='Заголовка-1')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовка-2')),
                ('title3', models.CharField(max_length=155, verbose_name='Заголовка-3')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Строница о нас',
            },
        ),
    ]
