# Generated by Django 5.0 on 2024-01-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_aboutmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='icon',
            field=models.CharField(choices=[('Бесплатная доставка', 'Бесплатная доставка'), ('Высококачественный продукт', 'Высококачественный продукт'), ('100% натуральный кофе', '100% натуральный кофе')], default=1, max_length=155, verbose_name='Иконки'),
            preserve_default=False,
        ),
    ]
