# Generated by Django 5.0 on 2024-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_about_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
