# Generated by Django 5.0 on 2024-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_blog_rename_contacts_сontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='сontacts',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='сontacts',
            name='message',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
    ]
